INSERT INTO ndpa_sections (section_id, title, content, plain_summary, keywords, language) VALUES
('24', 'Principles of Processing', 'Data controllers and processors shall ensure that personal data is processed lawfully, fairly, and transparently.', 'Personal data must be processed according to legal principles.', ARRAY['principles', 'lawful', 'fair', 'transparent'], 'en'),
('25', 'Lawful Basis', 'Processing shall be lawful only if a lawful basis applies.', 'Data processing requires a valid legal basis like consent or contract.', ARRAY['lawful basis', 'consent', 'contract', 'legitimate interest'], 'en'),
('26', 'Consent', 'Consent must be freely given, specific, informed, and unambiguous.', 'Consent requires clear affirmative action.', ARRAY['consent', 'withdrawal', 'affirmative action'], 'en'),
('27', 'Transparency', 'Controllers must provide information in a concise, transparent form.', 'Organizations must clearly inform about data use.', ARRAY['transparency', 'privacy policy', 'notice'], 'en'),
('30', 'Sensitive Data', 'Processing of sensitive data is prohibited unless conditions apply.', 'Special restrictions for health, biometric, religious data.', ARRAY['sensitive data', 'health', 'biometric'], 'en'),
('31', 'Children', 'A child is any person under 18 years.', 'Children under 18 require parental consent.', ARRAY['children', 'minor', 'parental consent', 'under 18'], 'en'),
('32', 'DPO Appointment', 'Controllers of major importance must appoint a DPO.', 'Certain organizations must designate a Data Protection Officer.', ARRAY['DPO', 'data protection officer', 'governance'], 'en'),
('39', 'Security Measures', 'Implement appropriate technical and organizational measures.', 'Protect data with encryption and access controls.', ARRAY['security', 'encryption', 'access control'], 'en'),
('40', 'Breach Notification', 'Notify NDPC within 72 hours of becoming aware of a breach.', 'Report data breaches within 72 hours to NDPC.', ARRAY['breach', 'notification', '72 hours', 'NDPC'], 'en'),
('44', 'Registration', 'Data controllers of major importance must register with NDPC.', 'DCPMIs must register with the Commission.', ARRAY['registration', 'DCPMI', 'NDPC'], 'en');

-- Add Yoruba translations
INSERT INTO ndpa_sections (section_id, title, content, plain_summary, keywords, language) VALUES
('24', 'Àwọn Ìlànà Ṣíṣe Ìtọ́jú Dátà Ẹni', 'Àwọn alákòóso dátà àti àwọn olùṣètò dátà gbọ́dọ̀ rí i dájú pé wọ́n ṣètò dátà àdání lọ́nà tí ó bófin mu, lọ́nà òdodo, àti lọ́nà tí ó hàn gbangba. A gbọ́dọ̀ ṣètò rẹ̀ fún àwọn ète tí a sọ ní pàtó, tí ó hàn kedere, àti tí ó bófin mu. Dátà gbọ́dọ̀ jẹ́ èyí tí ó tó, tí ó bá ọ̀ràn mu, tí ó sì ní ààlà sí ohun tí ó pọn dandan. Dátà gbọ́dọ̀ jẹ́ èyí tí ó péye, tí a sì mú un ṣe déédéé. A kò gbọ́dọ̀ tọ́jú dátà ju bí ó ṣe pọn dandan lọ. A gbọ́dọ̀ ṣètò dátà pẹ̀lú àwọn ìgbésẹ̀ ààbò tí ó yẹ.', 'A gbọ́dọ̀ ṣètò dátà àdání gẹ́gẹ́ bí àwọn ìlànà òfin ti wí fún bíbófin mu, òdodo, ìṣípayá, ààlà ète, ìdínkù dátà, ìpéye, ààlà ìtọ́jú, àti ààbò.', ARRAY['ìlànà', 'bíbófin mu', 'òdodo', 'ìṣípayá', 'ààlà ète', 'ìdínkù dátà', 'ìpéye', 'ààlà ìtọ́jú', 'ààbò'], 'yo'),
('25', 'Ìdí Òfin Fún Ṣíṣètò Dátà Ẹni', 'Ṣíṣètò dátà àdání yóò jẹ́ èyí tí ó bófin mu nìkan tí ó bá jẹ́ pé ó kéré tán ọ̀kan nínú àwọn wọ̀nyí kan: ìyọ̀ǹda ẹni tí ó ni dátà, ìmúṣẹ àdéhùn, ìbámu pẹ̀lú ojúṣe òfin, dídáàbòbo àwọn ire pàtàkì, ìṣe iṣẹ́ fún ire gbogbogbò, tàbí àwọn ire tí ó bófin mu tí alákòóso tàbí ẹnìkan kẹta ń lépa.', 'Ṣíṣètò dátà nílò ìdí òfin tí ó wúlò bíi ìyọ̀ǹda, àdéhùn, ojúṣe òfin, àwọn ire pàtàkì, ire gbogbogbò, tàbí àwọn ire tí ó bófin mu.', ARRAY['ìdí òfin', 'ìyọ̀ǹda', 'àdéhùn', 'ojúṣe òfin', 'àwọn ire pàtàkì', 'ire gbogbogbò', 'ire tí ó bófin mu'], 'yo'),
('26', 'Ìyọ̀ǹda', 'Ìyọ̀ǹda ẹni tí ó ni dátà túmọ̀ sí ìfihàn ìfẹ́ ẹni tí ó ni dátà èyíkéyìí tí a fi fúnni láìrówó, tí ó jẹ́ pàtó, tí a mọ̀, àti tí kò ní àìdánilójú. Ìdákẹ́, àwọn àpótí tí a ti fi àmì sí tẹ́lẹ̀, tàbí àìṣe nǹkan kò ní jẹ́ ìyọ̀ǹda. Ẹni tí ó ni dátà ní ẹ̀tọ́ láti fagi lé ìyọ̀ǹda nígbàkúùgbà. Fífagi lé kò ní nípa lórí bí ó ṣe bófin mu láti ṣètò dátà tí a gbé karí ìyọ̀ǹda kí a tó fagi lé e.', 'Ìyọ̀ǹda gbọ́dọ̀ jẹ́ èyí tí a fi fúnni láìrówó, tí ó jẹ́ pàtó, tí a mọ̀, àti tí kò ní àìdánilójú nípasẹ̀ ìṣe tí ó hàn kedere. A lè fagi lé e nígbàkúùgbà.', ARRAY['ìyọ̀ǹda', 'fífagi lé', 'ìṣe tí ó hàn kedere', 'tí a mọ̀', 'tí a fi fúnni láìrówó', 'pàtó', 'tí kò ní àìdánilójú'], 'yo'),
('27', 'Ìṣípayá àti Àwọn Ojúṣe Ìfitónilétí', 'Alákòóso yóò gbé àwọn ìgbésẹ̀ tí ó yẹ láti pèsè ìfitónilétí tí ó kan ṣíṣètò fún ẹni tí ó ni dátà ní ọ̀nà ṣókí, tí ó hàn gbangba, tí ó ní òye, àti tí ó rọrùn láti wọlé sí, ní lílo èdè tí ó ṣe kedere àti tí ó rọrùn. A gbọ́dọ̀ pèsè ìfitónilétí ní kíkọ tàbí nípasẹ̀ àwọn ọ̀nà mìíràn pẹ̀lú àwọn ọ̀nà ìbánisọ̀rọ̀ ẹ̀rọ.', 'Àwọn àjọ gbọ́dọ̀ sọ fún àwọn ẹni kọ̀ọ̀kan lọ́nà tí ó ṣe kedere bí wọ́n ṣe ń ṣètò dátà àdání wọn, ní èdè tí ó ṣe kedere àti tí ó rọrùn.', ARRAY['ìṣípayá', 'ètò àṣírí', 'ìfitónilétí', 'ìkìlọ̀', 'èdè tí ó rọrùn', 'tí ó rọrùn láti wọlé sí'], 'yo'),
('30', 'Dátà Ẹni Àkànṣe', 'Ṣíṣètò dátà àdání tí ń ṣípayá ẹ̀yà ìran tàbí ìpìlẹ̀ ẹ̀yà, àwọn èrò òṣèlú, àwọn ìgbàgbọ́ ẹ̀sìn tàbí ti ìmọ̀ ọgbọ́n orí, jíjẹ́ ọmọ ẹgbẹ́ òṣìṣẹ́, dátà apilẹ̀ àbùdá, dátà onínú ara, dátà ìlera, tàbí dátà tí ó kan ìgbésí ayé ìbálòpọ̀ tàbí ìṣesí ìbálòpọ̀ jẹ́ èyí tí a kà léèwọ̀ àyàfi tí àwọn ipò pàtó bá wà.', 'Àwọn ìhámọ́ pàtàkì kan àwọn dátà àkànṣe tí ó ní ìsọfúnni ìlera, onínú ara, àwọn ìgbàgbọ́ ẹ̀sìn, àwọn èrò òṣèlú, àti ìṣesí ìbálòpọ̀.', ARRAY['dátà àkànṣe', 'ìlera', 'onínú ara', 'apilẹ̀ àbùdá', 'àwọn ẹ̀ka pàtàkì', 'ẹ̀yà', 'ẹ̀sìn', 'òṣèlú'], 'yo'),
('31', 'Ṣíṣètò Dátà Àwọn Ọmọdé', 'Ọmọdé jẹ́ ẹnikẹ́ni tí kò tí ì pé ọmọ ọdún 18. Níbi tí ṣíṣètò bá kan fífi àwọn iṣẹ́ àwùjọ ìsọfúnni fún ọmọdé ní tààrà, ìyọ̀ǹda yóò jẹ́ fífúnni tàbí fífọwọ́sí láti ọwọ́ ẹni tí ó ní ẹ̀tọ́ àbójútó òbí. Alákòóso yóò gbìyànjú tí ó bọ́gbọ́n mu láti fìdí rẹ̀ múlẹ̀ pé ẹni tí ó ní ẹ̀tọ́ àbójútó òbí ló fúnni ní ìyọ̀ǹda.', 'Àwọn ọmọdé tí kò tí ì pé 18 nílò ìyọ̀ǹda òbí fún ṣíṣètò dátà. Àwọn àjọ gbọ́dọ̀ fìdí ìyọ̀ǹda òbí múlẹ̀.', ARRAY['àwọn ọmọdé', 'ọ̀dọ́', 'ìyọ̀ǹda òbí', 'lábẹ́ 18', 'ìfìdímúlẹ̀'], 'yo'),
('32', 'Ọ̀gá Ààbò Dátà', 'Alákòóso dátà tí ó ṣe pàtàkì yóò yan Ọ̀gá Ààbò Dátà. DPO yóò ní ìmọ̀ ìjìnlẹ̀ ti òfin àti àwọn ìlò ìdáàbòbò dátà. DPO lè jẹ́ ọmọ ẹgbẹ́ òṣìṣẹ́ tàbí kí ó mú àwọn iṣẹ́ ṣe lórí àdéhùn iṣẹ́.', 'Àwọn àjọ tí ó bá dé àwọn ààlà kan gbọ́dọ̀ yan Ọ̀gá Ààbò Dátà tí ó ní ìmọ̀ ìjìnlẹ̀.', ARRAY['DPO', 'ọ̀gá ààbò dátà', 'yíyàn', 'ìṣàkóso', 'ìbámu', 'ìjìnlẹ̀'], 'yo'),
('39', 'Ààbò Ṣíṣètò', 'Alákòóso àti olùṣètò yóò mú àwọn ìgbésẹ̀ ìmọ̀ ẹ̀rọ àti ti ètò tí ó yẹ láti mú kí ìpele ààbò tí ó bá ewu mu wà. Àwọn ìgbésẹ̀ lè ní ìfarawe ìdánimọ̀, ìpamọ́ kóòdù, rírí i dájú pé àṣírí, ìṣòótó, wíwàlọ́wọ́, àti agbára ìmúpadà àwọn ètò ṣíṣètò wà.', 'Àwọn àjọ gbọ́dọ̀ dáàbò bo dátà àdání pẹ̀lú ìpamọ́ kóòdù, àwọn ìṣàkóso wíwọlé, àti àwọn ìlànà ààbò tí ó bá ewu mu.', ARRAY['ààbò', 'ìpamọ́ kóòdù', 'ìfarawe ìdánimọ̀', 'àṣírí', 'ìṣòótó', 'wíwàlọ́wọ́', 'agbára ìmúpadà'], 'yo'),
('40', 'Ìfitónilétí Ìrúfin Dátà Ẹni', 'Ní ọ̀ràn ìrúfin dátà àdání, alákòóso yóò fi tó Kọmíṣọ́nnà létí láìsí àìdára ìgbàdégbà àti, níbi tí ó bá ṣeéṣe, kí ó má tó wákàtí 72 lẹ́yìn tí ó ti mọ̀ nípa rẹ̀. Níbi tí ìrúfin náà bá lè yọrí sí ewu gíga fún àwọn ẹni tí ó ni dátà, alákòóso yóò tún fi ìrúfin náà sọ fún ẹni tí ó ni dátà.', 'Jábọ̀ ìrúfin dátà fún NDPC láàárín wákàtí 72. Sọ fún àwọn ẹni tí ó kàn án bí ìrúfin náà bá jẹ́ ewu gíga.', ARRAY['ìrúfin', 'ìfitónilétí', 'wákàtí 72', 'NDPC', 'jíjábọ̀', 'ìdáhùn sí ìṣẹ̀lẹ̀'], 'yo'),
('44', 'Ìforúkọsílẹ̀ Àwọn Alákòóso Dátà àti Àwọn Olùṣètò', 'Àwọn alákòóso dátà àti àwọn olùṣètò tí ó ṣe pàtàkì yóò forúkọsílẹ̀ lọ́dọ̀ Kọmíṣọ́nnà láàárín oṣù mẹ́fà tí Òfin bá ti bẹ̀rẹ̀ tàbí nígbà tí wọ́n bá dé ipò yẹn. Ìforúkọsílẹ̀ yóò ní àwọn ẹ̀kúnrẹ́rẹ́ àwọn ìgbòkègbodò ṣíṣètò, àwọn ẹni tí ó ni dátà, àwọn ète, àwọn olùgbà, àti àwọn ìgbésẹ̀ ààbò.', 'Àwọn àjọ tí a pín sí Alákòóso Dátà tàbí Olùṣètò Dátà Tí Ó Ṣe Pàtàkì gbọ́dọ̀ forúkọsílẹ̀ lọ́dọ̀ NDPC kí wọ́n sì pèsè àwọn ẹ̀kúnrẹ́rẹ́ nípa ṣíṣètò dátà wọn.', ARRAY['ìforúkọsílẹ̀', 'DCPMI', 'NDPC', 'fífisílẹ̀', 'ìbámu'], 'yo'),
('48', 'Àwọn Àṣẹ Ìmúṣẹ àti Àwọn Ìtanràn', 'Lẹ́yìn ìwádìí, Kọmíṣọ́nnà lè gbé àwọn àṣẹ ìmúṣẹ jáde tí ó nílò àtúnṣe, sísan ẹ̀san, tàbí sísan owó ìtanràn. Ìtanràn tí ó pọ̀ jùlọ fún àwọn alákòóso tí ó ṣe pàtàkì: ₦10,000,000 tàbí 2% ti owó tí wọ́n ń gbà lọ́dún, èyíkéyìí tí ó bá pọ̀ jù.', 'Ìrúfin lè yọrí sí ìtanràn tí ó tó Nàìrà mílíọ̀nù 10 tàbí 2% ti owó tí wọ́n ń gbà lọ́dún fún àwọn àjọ tí ó ṣe pàtàkì.', ARRAY['àwọn ìtanràn', 'owó ìtanràn', 'ìmúṣẹ', 'ẹ̀san', 'àwọn ìfìyàjẹni'], 'yo');


-- Add Hausa translations
INSERT INTO ndpa_sections (section_id, title, content, plain_summary, keywords, language) VALUES
('24', 'Ka''idojin Sarrafa Bayanan Mutum', 'Duk mai sarrafa bayani ko mataimakinsa ya tabbatar cewa bayanai na mutum: a yi adalci a wajen sarrafa shi, halattacce, da kuma adalci. A karbi bayanin domin dalili halattacce kuma zahiri. Ya shafa kuma ya takaita ga wadannan dalilai. A adana bayanan gwargwadon bukatarsa. Ya yi daidai, kammalalle, ba mai batarwa ba. A sarrafa bisa tsaro domin kare wadanda ba su cancanta su samu bayanin ba.', 'Dole a sarrafa bayanan sirri bisa ka''idojin doka na halatta, adalci, gaskiya, iyakance manufa, rage bayanai, daidaito, iyakance ajiya, da tsaro.', ARRAY['ka''idoji', 'halatta', 'adalci', 'gaskiya', 'iyakance manufa', 'rage bayanai', 'daidaito', 'iyakance ajiya', 'tsaro'], 'ha'),
('25', 'Halattaccen Dalilin Sarrafa Bayanai', 'Doka ta yarda a sarrafa bayanan mutum idan daya daga cikin wadannan ya faru: yardar mai bayani, aiwatar da kwangila, bin wajibcin doka, kare muhimman bukatun mutum, aiwatar da aikin jama''a, ko bukatun halal na mai sarrafa bayani ko wani na uku.', 'Sarrafa bayanai na bukatar ingantaccen tushe na doka kamar yarda, kwangila, wajibcin doka, muhimman bukatu, bukatun jama''a, ko halaltattun bukatu.', ARRAY['tushen doka', 'yarda', 'kwangila', 'wajibcin doka', 'muhimman bukatu', 'bukatun jama''a', 'halaltattun bukatu'], 'ha'),
('26', 'Yarda', 'Yarda shi ne yardar mutum ta hanyar furuci ko a rubuce, ko a aikace ta ba da dama a yi amfani da bayanan sirrinsu. Shiru ba yarda ba ne. Mai bayani yana da hakkin janye yardarsa a kowane lokaci. Janyewa ba zai shafi halaccin sarrafa bayanan da aka yi kafin janyewar ba.', 'Dole yarda ta kasance ta son rai, takamaimai, sanarwa, kuma babu shakka ta hanyar tabbataccen aiki. Ana iya janye ta kowane lokaci.', ARRAY['yarda', 'janyewa', 'tabbataccen aiki', 'sanarwa', 'son rai', 'takamaimai', 'babu shakka'], 'ha'),
('27', 'Gaskiya da Wajibcin Bayar da Bayani', 'Mai sarrafa bayani zai dauki matakan da suka dace don bayar da bayanin da ya shafi sarrafawa ga mai bayani a takaice, a bayyane, mai saukin fahimta, ta hanyar amfani da harshe bayyananne kuma mai sauki.', 'Dole kungiyoyi su sanar da mutane a fili yadda ake sarrafa bayanan sirrinsu, a harshe mai sauki.', ARRAY['gaskiya', 'manufar sirri', 'bayani', 'sanarwa', 'harshe mai sauki', 'mai saukin samu'], 'ha'),
('30', 'Bayanan Sirri Masu Muhimmanci', 'Sarrafa bayanan sirri da ke bayyana asalin launin fata ko kabila, ra''ayoyin siyasa, akidar addini ko falsafa, zama memba a kungiyar kwadago, bayanan kwayoyin halitta, bayanan nazarin halittu, bayanan lafiya, ko bayanan da suka shafi rayuwar jima''i ko yanayin jima''i haramun ne sai dai in takamaiman sharudda sun shafi.', 'Ƙuntatawa ta musamman ta shafi bayanai masu muhimmanci da suka haɗa da bayanan lafiya, nazarin halittu, akidar addini, ra''ayoyin siyasa, da yanayin jima''i.', ARRAY['bayanai masu muhimmanci', 'lafiya', 'nazarin halittu', 'kwayoyin halitta', 'rukunai na musamman', 'kabila', 'addini', 'siyasa'], 'ha'),
('31', 'Sarrafa Bayanan Yara', 'Yaro shi ne duk wanda bai kai shekara 18 ba. Inda sarrafawa ya shafi bayar da sabis na al''umma na bayanai kai tsaye ga yaro, yarda za a bayar ko a ba da izini daga mai alhakin iyaye. Mai sarrafawa zai yi ƙoƙari mai ma''ana don tabbatar da cewa mai alhakin iyaye ne ya ba da yarda.', 'Yara ''yan ƙasa da shekara 18 suna buƙatar yardar iyaye don sarrafa bayanai. Dole kungiyoyi su tabbatar da yardar iyaye.', ARRAY['yara', 'ƙanana', 'yardar iyaye', 'ƙasa da 18', 'tabbatarwa'], 'ha'),
('32', 'Jami''in Kare Bayanai', 'Mai sarrafa bayanai mai muhimmanci zai nada Jami''in Kare Bayanai. DPO zai kasance yana da ƙwararrun ilimin dokar kare bayanai da ayyuka. Ana iya ɗaukar DPO a matsayin ma''aikaci ko kuma ya cika ayyuka bisa kwangilar sabis.', 'Ƙungiyoyin da suka cika wasu ƙa''idodi dole su nada Jami''in Kare Bayanai mai ƙwararrun ilimi.', ARRAY['DPO', 'jami''in kare bayanai', 'nada', 'shugabanci', 'bin doka', 'ƙwararre'], 'ha'),
('39', 'Tsaron Sarrafawa', 'Mai sarrafawa da mai aiwatarwa za su aiwatar da matakan fasaha da na ƙungiya da suka dace don tabbatar da matakin tsaro wanda ya dace da haɗarin. Matakan na iya haɗawa da ɓoye suna, ɓoye bayanai, tabbatar da sirri, mutunci, samuwa, da juriya na tsarin sarrafawa.', 'Dole kungiyoyi su kare bayanan sirri tare da ɓoye bayanai, sarrafa damar shiga, da manufofin tsaro da suka dace da haɗarin.', ARRAY['tsaro', 'ɓoye bayanai', 'ɓoye suna', 'sirri', 'mutunci', 'samuwa', 'juriya'], 'ha'),
('40', 'Sanarwar ɓoyewar Bayanan Sirri', 'A yayin ɓoyewar bayanan sirri, mai sarrafawa zai sanar da Hukumar ba tare da bata lokaci ba kuma, inda ya yiwu, ba a wuce sa''o''i 72 da sanin faruwar hakan ba. Inda ɓoyewar ke iya haifar da babban haɗari ga masu bayanin, mai sarrafawa zai kuma sanar da mai bayanin.', 'A ba da rahoton ɓoyewar bayanai ga NDPC cikin sa''o''i 72. Sanar da mutanen da abin ya shafa idan ɓoyewar tana da babban haɗari.', ARRAY['ɓoyewa', 'sanarwa', 'sa''o''i 72', 'NDPC', 'bayar da rahoto', 'amsa lamarin'], 'ha'),
('44', 'Rajistar Masu Sarrafa Bayanai da Masu Aiwa tarwa', 'Masu sarrafa bayanai da masu aiwatarwa masu muhimmanci za su yi rajista da Hukumar cikin watanni shida na fara aiki da Dokar ko kuma bayan sun sami wannan matsayi. Rajista za ta haɗa da cikakkun bayanai na ayyukan sarrafawa, masu bayanin, dalilai, masu karɓa, da matakan tsaro.', 'Dole kungiyoyin da aka lasafta a matsayin Masu Sarrafa Bayanai ko Masu Aiwa tarwa Masu Muhimmanci su yi rajista da NDPC tare da samar da cikakkun bayanai game da sarrafa bayanansu.', ARRAY['rajista', 'DCPMI', 'NDPC', 'gabatarwa', 'bin doka'], 'ha'),
('48', 'Umurnin Tilastawa da Hukunci', 'Bayan bincike, Hukumar za ta iya bayar da umarnin tilastawa da ke buƙatar gyara, biyan diyya, ko biyan tara. Matsakaicin hukunci ga masu sarrafawa masu muhimmanci: ₦10,000,000 ko 2% na kudaden shiga na shekara, wanda ya fi girma.', 'Keta doka na iya haifar da tarar har zuwa Naira miliyan 10 ko 2% na kudaden shiga na shekara ga hukumomi masu muhimmanci.', ARRAY['hukunci', 'tara', 'tilastawa', 'diyya', 'takunkumi'], 'ha');

-- Add Igbo translations
INSERT INTO ndpa_sections (section_id, title, content, plain_summary, keywords, language) VALUES
('24', 'Ụkpụrụ nke Nhazi Data Onwe', 'Ndị na-achịkwa data na ndị na-eme data ga-ahụ na a na-ahazi data onwe n''ụzọ iwu kwadoro, n''ụzọ ziri ezi, na n''ụzọ doro anya. A ga-ahazi ya maka ebumnuche akọwapụtara, doro anya na nke ziri ezi. Data ga-abụ nke zuru oke, dabara adaba, ma bụrụ nke a kpaara ókè n''ihe dị mkpa. Data ga-abụ nke ziri ezi ma debe ya ọhụrụ. A gaghị edebe data karịa ka ọ dị mkpa. A ga-ahazi data site na iji usoro nchekwa kwesịrị ekwesị.', 'A ga-ahazirịrị data onwe dịka ụkpụrụ iwu siri dị nke iwu kwadoro, izi ezi, nghọta, mmachi nzube, mbelata data, izi ezi, mmachi nchekwa, na nchekwa.', ARRAY['ụkpụrụ', 'iwu kwadoro', 'izi ezi', 'nghọta', 'mmachi nzube', 'mbelata data', 'izi ezi', 'mmachi nchekwa', 'nchekwa'], 'ig'),
('25', 'Ntọala Iwu Kwadoro Maka Nhazi Data', 'Nhazi data onwe ga-abụ nke iwu kwadoro naanị ma ọ bụrụ na opekata mpe otu n''ime ihe ndị a metụtara: nkwenye nke onye nwe data, ịrụ ọrụ nkwekọrịta, irube isi n''ọrụ iwu, ichebe ọdịmma dị mkpa, ịrụ ọrụ maka ọdịmma ọha, ma ọ bụ ọdịmma ziri ezi nke onye na-achịkwa ma ọ bụ onye nke atọ.', 'Nhazi data chọrọ ntọala iwu ziri ezi dị ka nkwenye, nkwekọrịta, ọrụ iwu, ọdịmma dị mkpa, ọdịmma ọha, ma ọ bụ ọdịmma ziri ezi.', ARRAY['ntọala iwu', 'nkwenye', 'nkwekọrịta', 'ọrụ iwu', 'ọdịmma dị mkpa', 'ọdịmma ọha', 'ọdịmma ziri ezi'], 'ig'),
('26', 'Nkwenye', 'Nkwenye nke onye nwe data pụtara ngosipụta ọ bụla e nyere n''efu, nke akọwapụtara, nke a maara, na nke doro anya nke ọchịchọ onye nwe data. Ịgbachi nkịtị, igbe ndị e bu ụzọ tụọ, ma ọ bụ emeghị ihe ọ bụla abụghị nkwenye. Onye nwe data nwere ikike ịwepụ nkwenye n''oge ọ bụla. Mwepụ agaghị emetụta izi ezi nke nhazi dabere na nkwenye tupu mwepụ.', 'Nkwenye ga-abụ nke e nyere n''efu, nke akọwapụtara, nke a maara, na nke doro anya site na omume doro anya. Enwere ike ịwepụ ya n''oge ọ bụla.', ARRAY['nkwenye', 'mwepu', 'omume doro anya', 'nke a maara', 'nke e nyere n''efu', 'nke akọwapụtara', 'nke doro anya'], 'ig'),
('27', 'Nghọta na Ọrụ Ozi', 'Onye na-achịkwa ga-eme ihe kwesịrị ekwesị iji nye ozi gbasara nhazi nye onye nwe data n''ụdị nkenke, nghọta, nwere ọgụgụ isi, na nke dị mfe ịnweta, na-eji asụsụ doro anya ma dị mfe nghọta.', 'Ụlọ ọrụ ga-agwara ndị mmadụ n''ụzọ doro anya otu esi ahazi data onwe ha, n''asụsụ doro anya ma dị mfe.', ARRAY['nghọta', 'amụma nzuzo', 'ozi', 'ọkwa', 'asụsụ doro anya', 'dị mfe ịnweta'], 'ig'),
('30', 'Data Onwe Dị Nro', 'Nhazi data onwe nke na-ekpughe agbụrụ ma ọ bụ agbụrụ mmadụ, echiche ndọrọ ndọrọ ọchịchị, nkwenye okpukpe ma ọ bụ nkà ihe ọmụma, ịbụ onye otu ọrụ, data mkpụrụ ndụ ihe nketa, data biometric, data ahụike, ma ọ bụ data gbasara mmekọahụ ma ọ bụ usoro mmekọahụ ga-abụ nke a machibidoro iwu ma ọ gwụla ma ọnọdụ akọwapụtara metụtara.', 'Mmachi pụrụ iche metụtara data dị nro gụnyere ozi ahụike, biometric, nkwenye okpukpe, echiche ndọrọ ndọrọ ọchịchị, na usoro mmekọahụ.', ARRAY['data dị nro', 'ahụike', 'biometric', 'mkpụrụ ndụ ihe nketa', 'udi pụrụ iche', 'agbụrụ', 'okpukpe', 'ndọrọ ndọrọ ọchịchị'], 'ig'),
('31', 'Nhazi Data Ụmụaka', 'Nwata bụ onye ọ bụla na-erubeghị afọ 18. Ebe nhazi metụtara inye ọrụ ọha ozi ozugbo nye nwata, a ga-enye nkwenye ma ọ bụ nyekwa ya ikike site n''aka onye ji ọrụ nne na nna. Onye na-achịkwa ga-agba mbọ ezi uche dị na ya iji chọpụta na onye ji ọrụ nne na nna nyere nkwenye.', 'Ụmụaka na-erubeghị afọ 18 chọrọ nkwenye nne na nna maka nhazi data. Ụlọ ọrụ ga-enyocha nkwenye nne na nna.', ARRAY['ụmụaka', 'onye na-erubeghị afọ', 'nkwenye nne na nna', 'n''okpuru 18', 'nyocha'], 'ig'),
('32', 'Onye Ọrụ Nchekwa Data', 'Onye na-achịkwa data dị oke mkpa ga-ahọpụta Onye Ọrụ Nchekwa Data. DPO ga-enwe ọkachamara n''ihe gbasara iwu na omume nchekwa data. DPO nwere ike ịbụ onye ọrụ ma ọ bụ mezuo ọrụ na nkwekọrịta ọrụ.', 'Ụlọ ọrụ ndị ruru ụfọdụ ọnụ ụzọ ga-ahọpụta Onye Ọrụ Nchekwa Data nwere ihe ọmụma ọkachamara.', ARRAY['DPO', 'onye ọrụ nchekwa data', 'nhọpụta', 'ọchịchị', 'nrubeisi', 'ọkachamara'], 'ig'),
('39', 'Nchekwa nke Nhazi', 'Onye na-achịkwa na onye na-eme data ga-emejuputa usoro nka na ụzụ na nhazi kwesịrị ekwesị iji hụ na nchekwa kwekọrọ n''ihe ize ndụ. Usoro nwere ike ịgụnye pseudonymization, izo ya ezo, ịhụ na nzuzo, iguzosi ike n''ezi ihe, ịdị adị, na nkwụsi ike nke usoro nhazi.', 'Ụlọ ọrụ ga-echekwa data onwe site na izo ya ezo, njikwa ohere, na amụma nchekwa dabara na ihe ize ndụ.', ARRAY['nchekwa', 'izo ya ezo', 'pseudonymization', 'nzuzo', 'iguzosi ike n''ezi ihe', 'ịdị adị', 'nkwụsi ike'], 'ig'),
('40', 'Ọkwa Mgbasa Ozi Maka Mmebi Data Onwe', 'N''ihe gbasara mmebi data onwe, onye na-achịkwa ga-agwa Kọmishọn n''egbughị oge na, ebe o kwere omume, n''ime awa 72 mgbe ọ matara ya. Ebe mmebi ahụ nwere ike ibute nnukwu ihe ize ndụ nye ndị nwe data, onye na-achịkwa ga-agwakwa onye nwe data banyere mmebi ahụ.', 'Kọọrọ NDPC mmebi data n''ime awa 72. Gwa ndị emetụtara ma ọ bụrụ na mmebi ahụ nwere nnukwu ihe ize ndụ.', ARRAY['mmebi', 'ọkwa', 'awa 72', 'NDPC', 'ịkọ akụkọ', 'nzaghachi merenụ'], 'ig'),
('44', 'Ndebanye Aha nke Ndị Na-achịkwa Data na Ndị Na-eme Data', 'Ndị na-achịkwa data na ndị na-eme data dị oke mkpa ga-edebanye aha na Kọmishọn n''ime ọnwa isii nke mmalite Iwu ahụ ma ọ bụ mgbe ha ruru ọnọdụ ahụ. Ndebanye aha ga-agụnye nkọwa nke ọrụ nhazi, ndị nwe data, ebumnuche, ndị nnata, na usoro nchekwa.', 'Ụlọ ọrụ ndị a kọwara dị ka Ndị Na-achịkwa Data ma ọ bụ Ndị Na-eme Data Dị Oke Mkpa ga-edebanye aha na NDPC ma nye nkọwa gbasara nhazi data ha.', ARRAY['ndebanye aha', 'DCPMI', 'NDPC', 'ịgba akwụkwọ', 'nrubeisi'], 'ig'),
('48', 'Iwu Mmanye na Ntaramahụhụ', 'Mgbe nyochachara, Kọmishọn nwere ike ịnye iwu mmanye nke chọrọ ndozi, ịkwụ ụgwọ, ma ọ bụ ịkwụ ụgwọ ntaramahụhụ. Ntaramahụhụ kachasị maka ndị na-achịkwa dị oke mkpa: ₦10,000,000 ma ọ bụ 2% nke ego ha nwetara n''afọ, nke ọ bụla ka ukwuu.', 'Mmebi iwu nwere ike ibute ntaramahụhụ ruru nde Naira 10 ma ọ bụ 2% nke ego ha nwetara n''afọ maka ụlọ ọrụ dị oke mkpa.', ARRAY['ntaramahụhụ', 'ụgwọ', 'mmanye', 'nkwụghachi ụgwọ', 'mmachi'], 'ig');